[sums]
min = 5
# minimum field size (4 - 15)
max = 13
# maximum field size (4 - 15, >= min)
mode = P
# A = all  - returns the second-order differential uniformities for all functions in 'n (sum).csv'
# P = part - faster but only returns the optimal functions in 'optimal (sum).csv'

[mults]
min = 4
# minimum field size (4 - 15)
max = 10
# maximum field size (4 - 15, >= min)

[grassmann]
min = 4
# minimum field size (4 - 13)
max = 10
# maximum field size (4 - 13, >= min)

[search]
min = 3
# minimum field size (3 - 5)
max = 5
# maximum field size (3 - 5, >= min)

[classify]
n = 5
# field size (only works with 5)