[sums]
min = 4
# minimum field size (4 - 32)
max = 4
# maximum field size (4 - 32, >= min)
mode = A
# A = all  - returns the second-order differential uniformities for all functions in 'n (sum).csv'
# P = part - faster but only returns the optimal functions in 'optimal (sum).csv'

[mults]
min = 4
# minimum field size (4 - 15)
max = 10
# maximum field size (4 - 15, >= min)

[grassmann]
min = 4
# minimum field size (4 - 15)
max = 5
# maximum field size (4 - 15, >= min)

[search]
min = 3
# minimum field size (3 - 6)
max = 5
# maximum field size (3 - 6, >= min)

[classify]
n = 5
# field size (only works with 5)